version: '3'
services:

  client:
    build: 
      context: client
      dockerfile: Dockerfile.prod
    container_name: dany-codes
    ports: 
      - 0.0.0.0:80:80
    volumes:
      - /home/node/app/node_modules
      - ./client/src:/home/node/app/src