backend:
  name: git-gateway # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: main # Branch to update
  repo: danydodson/dany.codes # Repo for pushing new commits. Make sure to replace with your repo!

media_library:
  name: cloudinary
  config:
    cloud_name: dany
    api_key: '282549924735476'

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: "Post"
    folder: "content"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}.md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Template', name: 'template', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - {
          label: 'Feed priority',
          name: 'priority',
          widget: 'number',
          default: 0,
          valueType: 'int',
        }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }

  - name: 'pages'
    label: 'Pages'
    folder: 'content/pages'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Template', name: 'template', widget: 'hidden', default: 'page' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - {
          label: 'Feed priority',
          name: 'priority',
          widget: 'number',
          default: 0,
          valueType: 'int',
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }